### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by heumn** [heumn/NJHIssueReporter#4]
<img width="632" alt="skjermbilde 2015-07-26 kl 15 48 56" src="https://cloud.githubusercontent.com/assets/1769314/8894199/dee82c94-33ad-11e5-9b2d-47783caa293a.png">

**Comment by hhanesand** [comment]
weird... I wasn't getting this warning
![screen shot 2015-07-26 at 22 35 15](https://cloud.githubusercontent.com/assets/3051243/8895839/59a37d96-33e8-11e5-9613-730ccfd43e17.png)

**Comment by hhanesand** [comment]
fixed it anyways though (I hope)
